---
name: Hotspot wifi pour RPI
version: 0.0.20
slug: hotspot_wifi
description: Addon Hotspot wifi with raspap-webgui
url: https://github.com/stasisha/Hassio-addons/tree/master/hotspot_wifi
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
startup: application
arch:
- armv7
map:
- config:rw
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface
options:
 internet: true
schema:
 internet: "bool"
boot: manual
host_network: true
hassio_api: true
hassio_role: default
auth_api: true
full_access: true
options: {}
schema: {}
privileged:
- NET_ADMIN
stage: experimental
